displayName=Dopamine Enhancer
author=scientaster
description=Adds celebratory effects and sounds for quests, collection log entries, and bank withdraws.
tags=quest,collection,log,bank,sound,effects
plugins=com.dopamineenhancer.DopamineEnhancerPlugin
build=standard
